name: Deploy to One.com

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: GitHub Deploy to One.com
        uses: rostimelk/one.com-deployer@master
        env:
          ONE_DOMAIN_NAME: genuinelyfun.com
          #ONE_SSH_KEY_PUBLIC: ${{ secrets.NGHI_MAIN_PC_PUBLIC }}
          #ONE_SSH_KEY_PRIVATE: ${{ secrets.NGHI_MAIN_PC_PRIVATE }}
          ONE_SSH_KEY_PUBLIC: ${{ secrets.ARTHUR_WORK_PC_PUBLIC }}
          ONE_SSH_KEY_PRIVATE: ${{ secrets.ARTHUR_WORK_PC_PRIVATE }}